#!/usr/bin/env node

var Z80 = require('../z80');

if(process.argv.length > 4 || process.argv.length === 2) {
  console.log("js80asm <input.asm> [output.rom]");
  process.exit(1);
}

var input = process.argv[2];
var output = 'a.out';

if(process.argv.length == 4) {
  output = process.argv[3];
}

var z80 = new Z80();
try {
  z80.compileFile(input);
} catch(e) {
  console.log('%s:%s: %s', z80.currentFilename, e.line, e.name||e);
}
z80.saveImage(output);
