#!/usr/bin/env node

var Z80 = require('../z80')
  , fs = require('fs');

if(process.argv.length > 4 || process.argv.length === 2) {
  console.log("js80asm <input.asm> [output.rom]");
  process.exit(1);
}

var input = process.argv[2];
var output = 'a.out';

if(process.argv.length == 4) {
  output = process.argv[3];
}

var data = fs.readFileSync(input, 'utf8');
var z80 = new Z80();
z80.asm(data);
z80.saveImage(output);
