#!/usr/bin/env node

var Z80 = require('../z80')
  , fs = require('fs');

if(process.argv.length > 4 || process.argv.length === 2) {
  console.log("js80asm <input.asm> [output.rom]");
  process.exit(1);
}

var input = process.argv[2];
var output = 'a.out';

if(process.argv.length == 2) {
  output = process.argv[3];
}

fs.readFile(input, 'utf8', function(err, data) {
  if(err) {
    console.log(err);
  } else {
    var z80 = new Z80();
    z80.asm(data);
    z80.saveImage(output);
  }
});
